name: Tech Task
description: Công việc kỹ thuật (CI/Infra/Refactor/Chore) không phải feature trực tiếp
title: '[TECH] '
labels: ['type:chore']
body:
  - type: input
    id: area
    attributes:
      label: Area/Module
      placeholder: 'infra / ci / config / refactor / security / docs'
    validations:
      required: true
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: Mục tiêu kỹ thuật và lý do
      placeholder: 'Thiết lập CI lint/test/build để ...'
    validations:
      required: true
  - type: textarea
    id: deliverables
    attributes:
      label: Deliverables / Output
      description: Danh sách kết quả phải có để coi là Done
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
  - type: textarea
    id: approach
    attributes:
      label: Proposed Approach
      description: Cách làm dự kiến (ngắn gọn)
      placeholder: |
        - Step 1: ...
        - Step 2: ...
    validations:
      required: false
  - type: textarea
    id: risks
    attributes:
      label: Risks / Rollback
      description: Rủi ro và phương án rollback (nếu có)
      placeholder: |
        Risks:
        - ...
        Rollback:
        - ...
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - prio:P0
        - prio:P1
        - prio:P2
        - prio:P3
    validations:
      required: true
